- name: Download minio server
  get_url:
    url: https://dl.min.io/server/minio/release/linux-amd64/minio
    dest: "/usr/bin/minio"
    mode: 'a+x'
    owner: "{{ minio_username }}"

- name: Create a symbolic link
  ansible.builtin.file:
    src: /usr/bin/minio
    dest: /usr/local/bin/minio
    state: link

- name: Generate the Minio server envfile
  template:
    src: minio.env.j2
    dest: "/etc/default/minio"
    owner: "root"
    group: "{{ minio_username }}"
    mode: 0640

- name: Create systemd for minio
  get_url:
    url: https://raw.githubusercontent.com/minio/minio-service/master/linux-systemd/minio.service
    dest: "/etc/systemd/system/minio.service"
    owner: root
    group: root

- name: Restart service minio
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: minio
    enabled: yes
