# tasks file for ansible-role-minio-example
- name: Requirement & Prequisites to install MinIO
  ansible.builtin.include_tasks: prerequisites.yaml
- name: Install MinIO
  block:
    - name: Install server package
      ansible.builtin.include_tasks: install-minio-server.yaml
    - name: Install client package
      ansible.builtin.include_tasks: install-minio-client.yaml
